server:
  port: 8888 # TODO 自己定
spring:
  application:
    name: oomall-user # TODO 自己定
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.152.28:3306/oomall # TODO 自己定
    username: oomall # 自己定
    password: OOAD3-4wmtnl # 自己定
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 10
      #获取连接时最大等待时间
      max-wait: 60000
      #配置监控页面访问登录名及密码
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: admin
        login-password: 123456
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 100
      validation-query: select 1
  redis:
    host: 101.132.152.28 # TODO 自己定
    password: hyt123 # TODO 自己定
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://ooad33.top:8081/eureka/ # TODO 自己定

# 接下来都是zuul，其它配置请放上面
# TODO 自己定
serviceUrl: # 各模块地址，方便修改
  log: http://101.132.152.28:8082
  topic: http://101.132.152.28:8084
  cart:  http://101.132.152.28:8083
  ad: http://101.132.152.28:8086


# 下面不用改
zuul:
  host:
    max-total-connections: 10000
    max-per-route-connections: 50
  routes: #给服务配置路由
    user-service:
      path: /**/userInfoService/**
      url: forward:/
    log-service:
      path: /**/logService/**
      url: ${serviceUrl.log}
    topic-service:
      path: /**/topicService/**
      url: ${serviceUrl.topic}
    cart-service:
      path: /**/cartService/**
      url: ${serviceUrl.cart}
    ad-service:
      path: /**/adService/**
      url: ${serviceUrl.ad}
  sensitive-headers:  #配置过滤敏感的请求头信息，设置为空就不会过滤
  ignored-services: '*'
  add-host-header: true