server:
  port: 3400
spring:
  application:
    name: userInfoService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.52.88.176:3306/DB3_3
    username: user3_3
    password: ooad3
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 2
      #最大连接池数量
      max-active: 5
      #获取连接时最大等待时间
      max-wait: 60000
      #配置监控页面访问登录名及密码
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: admin
        login-password: 123456
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 100
      validation-query: select 1

  redis:
    host: 101.132.152.28
    password: hyt123
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://47.100.91.153:3500/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 101.132.152.28
    non-secure-port: 3400
#    ip-address: 192.168.1.145

# 接下来都是zuul，其它配置请放上面
zuul:
  host:
    max-total-connections: 10000
    max-per-route-connections: 50
  routes: #给服务配置路由
    userInfoService:
      path: /userInfoService/**
      url: forward:/
    logService:
      path: /logService/**
#      serviceId: logService
      url: http://101.132.152.28:3410
    adService:
      path: /adService/**
#      serviceId: adService
      url: http://101.132.152.28:3420
    afterSaleService:
      path: /afterSaleService/**
      serviceId: afterSaleService
    paymentService:
      path: /paymentService/**
#      serviceId: paymentService
      url: http://106.15.249.35:7777
    discountService:
      path: /discountService/**
#      serviceId: discountService
      url: http://60.205.212.233:3703
    collectionService:
      path: /collectionService/**
#      serviceId: collectionService
      url: http://47.100.91.153:3583
    commentService:
      path: /commentService/**
#      serviceId: commentService
      url: http://47.100.91.153:3450
    goodsInfoService:
      path: /goodsInfoService/**
#      serviceId: goodsInfoService
      url: http://47.100.91.153:3090
    topicService:
      path: /topicService/**
#      serviceId: topicService
      url: http://60.205.212.233:3700
    footprintService:
      path: /footprintService/**
#      serviceId: footprintService
      url: http://47.100.91.153:3568
    orderService:
      path: /orderService/**
#      serviceId: orderService
      url: http://106.15.249.35:3302
    cartService:
      path: /cartService/**
#      serviceId: cartService
      url: http://47.98.145.177:3525
    shareService:
      path: /shareService/**
#      serviceId: shareService
      url: http://106.15.249.35:3333
    freightService:
      path: /freightService/**
#      serviceId: freightService
      url: http://60.205.212.233:3701
    addressService:
      path: /addressService/**
#      serviceId: addressService
      url: http://47.98.145.177:3300
    logisticsService:
      path: /logisticsService/**
#      serviceId: logisticsService
      url: http://47.98.145.177:3299
    wxPaymentService:
      path: /wxPaymentService/**
#      serviceId: wxPaymentService
      url: http://106.15.249.35:7778
  sensitive-headers:  #配置过滤敏感的请求头信息，设置为空就不会过滤
  add-host-header: true
