server:
  port: 3302

spring:
  application:
    name: orderService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://47.52.88.176:3306/DB3_3
    username: user3_3
    password: ooad3
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      #初始化时建立物理连接的个数
#      initial-size: 3
#      #最小连接池数量
#      min-idle: 3
#      #最大连接池数量
#      max-active: 10
#      #获取连接时最大等待时间
#      max-wait: 60000
#      #配置监控页面访问登录名及密码
#      stat-view-servlet:
#        enabled: true
#        # 访问路径为/druid时，跳转到StatViewServlet
#        url-pattern: /druid/*
#        # 是否能够重置数据
#        reset-enable: false
#        # 需要账号密码才能访问控制台
#        login-username: admin
#        login-password: 123456
#      filter:
#        stat:
#          #是否开启慢sql查询监控
#          log-slow-sql: true
#          #慢SQL执行时间
#          slow-sql-millis: 100
#      validation-query: select 1

  redis:
    host: 101.132.152.28
    password: hyt123
    jedis:
      pool:
        max-active: 3 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 3 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 10000ms # 连接超时时间（毫秒）

eureka:
  client:
    service-url:
      defaultZone: http://ooad33.top:8081/eureka/
  instance:
    prefer-ip-address: true
      #    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
      #    lease-expiration-duration-in-seconds: 90
      #    lease-renewal-interval-in-seconds: 30
    #    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #    ip-address:  ${spring.cloud.client.ip-address}
#        ip-address: 127.0.0.1
    ip-address:  47.100.91.153
    non-secure-port: 3302