spring:
  profiles:
    active: dev

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info

mybatis:
  #domain对象的包（标准组的）
  type-aliases-package: xmu.oomall.domain
  #mapper.xml所在的位置
  mapper-locations: classpath:xmu.oomall.mapper/*.xml
  configuration:
    #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
    map-underscore-to-camel-case: true

logging:
  #设置日志打印级别
  level:
    #Spring框架中的日志级别
    org.springframework.web: info
    root: error
    #自己项目包名下的日志级别
    xmu.oomall.controller: debug
    xmu.oomall.service: debug
    xmu.oomall.dao: debug
    xmu.oomall.mapper: error
    xmu.oomall.domain: debug
    xmu.oomall.util: debug
  #使用logback日志，取代默认的common日志
  file:
    # TODO 记得修改
#    path: C:\Users\liznsalt\log
  config: classpath:logback-spring.xml

feign:
  hystrix:
    enabled: true
#  client:
#    config:
#      share:
#        connectTimeout: 120000
#        readTimeout: 120000
#  compression:
#    request:
#      enabled: true
#      mime-types: text/html,application/xml,application/json
#      min-request-size: 2048
#    response:
#      enabled: true

ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 600000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false