server:
  port: 9001

spring:
  application:
    name: zuul-eureka

eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://liznsalt:123456@peer1:9000/eureka/
  server:
    enable-self-preservation: false